version: "2"
services:
  app:
    image: clipmesh:nvidia #conda

    command: /bin/bash
    #command: bash -c 'source activate base && CUDA_HOME=/usr/local/cuda-11.3'
    deploy:
      resources: 
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]
              device_ids: ['1']

    container_name: clipmesh_${USER}
    user: ${CURRENT_UID}
    volumes:
      - /home/${USER}:/home/${USER}
      - /etc/passwd:/etc/passwd      
      - /etc/group:/etc/group
#    ports:
#      - "8888:8888"
    tty: true
    working_dir: $HOME
    #command: tail -f /dev/null
    stdin_open: true
