version: "2"
services:
  app:
    image: clipmesh:conda

    command: /bin/bash
    deploy:
      resources: 
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]
              device_ids: ['1']

    container_name: clipmesh_${USER}
    user: ${USER}
    volumes:
      - /home/${USER}:/home/${USER}
      - /etc/passwd:/etc/passwd      
      - /etc/group:/etc/group
    ports:
      - "8888:8888"
    tty: true
    working_dir: $HOME
    #command: tail -f /dev/null
    stdin_open: true
